# Generated by Django 4.2.6 on 2023-11-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_artworkspackage_packageorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="artworkspackage",
            name="defaultArtwork",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="collection.artwork",
            ),
        ),
        migrations.AddField(
            model_name="artworkspackage",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
