# Generated by Django 4.2.6 on 2023-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0004_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="packageorder",
            name="payment_intent",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
